# Generated by: Ollama Minimax

import os
import torch
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from datasets import Dataset
import json

# ==========================================
# 1. CONFIGURATION & PATHS
# ==========================================

# Model Config
MODEL_NAME = "unsloth/qwen2.5-coder-7b-bnb-4bit"
OUTPUT_DIR = "kart-ft" # This will be the folder name for GGUF export
MAX_SEQ_LENGTH = 2048  # Reduce if you run into OOM issues (e.g., 1024)

# LoRA Config
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.0

# Training Hyperparameters
EPOCHS = 3
LEARNING_RATE = 2e-4
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
WARMUP_STEPS = 10
OPTIMIZER = "paged_adamw_32bit"

# Data Paths
TRAINING_DATA_PATH = r"C:/Users/Sean/Documents/GitHub/aios-minimal/training/kart_training.jsonl"

# ==========================================
# 2. DEFINE KART SYSTEM PROMPT
# ==========================================
# REPLACE THIS with the exact personality/description from the Kart profile
KART_SYSTEM_PROMPT = "You are Kart, an AI assistant specialized in coding and automation."

# ==========================================
# 3. LOAD MODEL & TOKENIZER
# ==========================================
print(f"Loading base model: {MODEL_NAME}...")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=torch.bfloat16,
    load_in_4bit=True,
    # token = "hf_...", # Uncomment if using a gated model
)

print("Model loaded successfully.")

# ==========================================
# 4. SETUP LORA
# ==========================================
print("Setting up LoRA...")

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj", 
        "gate_proj", "up_proj", "down_proj"
    ],
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    bias="none",
    use_gradient_checkpointing="unsloth", # Reduces VRAM usage
    random_state=3407,
)

# ==========================================
# 5. LOAD & FORMAT DATA
# ==========================================
print(f"Loading data from {TRAINING_DATA_PATH}...")

def load_jsonl(file_path):
    data = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                data.append(json.loads(line))
    return data

raw_data = load_jsonl(TRAINING_DATA_PATH)

# We assume the JSONL contains fields like: {"instruction": "...", "input": "...", "output": "..."}
# If your JSONL is already ChatML messages, skip the formatting function and map directly.

def format_to_chatml(examples):
    text_list = []
    
    for example in examples:
        # Adjust these keys based on your actual JSONL structure
        # Assuming Alpaca-style: instruction + input -> user, output -> assistant
        
        instruction = example.get("instruction", "")
        user_input = example.get("input", "")
        response = example.get("output", "")

        # Construct the prompt
        user_content = f"{instruction}\n{user_input}".strip()
        
        # Create ChatML Message Structure
        messages = [
            {"role": "system", "content": KART_SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
            {"role": "assistant", "content": response}
        ]
        
        # Apply ChatML template
        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
        text_list.append(text)
        
    return {"text": text_list}

# Convert to datasets object
dataset = Dataset.from_list(raw_data)

# Map the formatting function
print("Formatting data to ChatML...")
dataset = dataset.map(format_to_chatml, batched=False, remove_columns=dataset.column_names)

# =================================6. INITIALIZE TRAINER
# ==========================================
print("Initializing SFTTrainer...")

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer),
    dataset_num_proc=2,
    packing=False, # Can set to True for shorter sequences to save VRAM
    args=TrainingArguments(
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        warmup_steps=WARMUP_STEPS,
        num_train_epochs=EPOCHS,
        learning_rate=LEARNING_RATE,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=10,
        optim=OPTIMIZER,
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir="logs",
        report_to="none", # Change to "wandb" if you want to track experiments
    ),
)

# ==========================================
# 7. TRAIN
# ==========================================
print("Starting training...")
trainer.train()

# ==========================================
# 8. SAVE AS GGUF FOR OLLAMA
# ==========================================
print(f"Saving model to GGUF in folder: {OUTPUT_DIR}...")

# Quantization method: q4_k_m is standard for good quality/size balance
model.save_pretrained_gguf(
    OUTPUT_DIR, 
    tokenizer, 
    quantization_method="q4_k_m"
)

print(f"Training complete! Model saved to ./{OUTPUT_DIR}")
print(f"To use in Ollama, create a Modelfile pointing to this directory or the .gguf file.")
