# Generated by: Ollama GLM-5 (llm_router)
import os
import time
import oci
from oci.config import from_file
from oci.core.models import (
    CreateVcnDetails, CreateInternetGatewayDetails, CreateRouteTableDetails,
    CreateSubnetDetails, CreateSecurityListDetails, LaunchInstanceDetails,
    CreateVnicDetails, LaunchInstanceShapeConfigDetails, InstanceSourceViaImageDetails,
    EgressSecurityRule, IngressSecurityRule, TcpOptions, PortRange, IcmpOptions
)
from oci.exceptions import ServiceError

# Configuration
COMPARTMENT_ID = None  # Will be read from config
VCN_CIDR = "10.0.0.0/16"
SUBNET_CIDR = "10.0.0.0/24"
IMAGE_ID = "ocid1.image.oc1.phx.aaaaaaaahzur55ghl5ypjy27zsuh7adac4ppnofrp2d3wuxu7iam4ibgkaia"
SHAPE = "VM.Standard.A1.Flex"
OCPUS = 4
MEMORY_IN_GBS = 24
BOOT_VOLUME_SIZE_GBS = 100
SSH_KEY_PATH = os.path.expanduser("~/.ssh/oracle_kart.pub")
RETRY_DELAY_SECONDS = 300  # 5 minutes between cycles to avoid rate limits

def print_step(message):
    print(f"[+] {message}")

def print_error(message):
    print(f"[-] {message}")

def read_ssh_key():
    print_step(f"Reading SSH key from {SSH_KEY_PATH}")
    try:
        with open(SSH_KEY_PATH, 'r') as f:
            return f.read().strip()
    except FileNotFoundError:
        print_error(f"SSH key not found at {SSH_KEY_PATH}. Please create it first.")
        exit(1)

def get_or_create_network(vcn_client, identity_client, compartment_id):
    print_step("Checking for existing VCN...")
    list_vcns = vcn_client.list_vcns(compartment_id)
    
    if list_vcns.data:
        vcn = list_vcns.data[0]
        print_step(f"Found existing VCN: {vcn.id}")
        
        # Get or create missing pieces
        igws = vcn_client.list_internet_gateways(compartment_id, vcn_id=vcn.id).data
        if not igws:
            igw = vcn_client.create_internet_gateway(oci.core.models.CreateInternetGatewayDetails(
                compartment_id=compartment_id, vcn_id=vcn.id, is_enabled=True, display_name="auto-igw"
            )).data
            print_step(f"Internet Gateway created: {igw.id}")
        else:
            igw = igws[0]

        # Ensure default route table points to IGW
        rts = vcn_client.list_route_tables(compartment_id, vcn_id=vcn.id).data
        if rts:
            vcn_client.update_route_table(rts[0].id, oci.core.models.UpdateRouteTableDetails(
                route_rules=[oci.core.models.RouteRule(
                    destination="0.0.0.0/0", destination_type="CIDR_BLOCK", network_entity_id=igw.id
                )]
            ))

        sec_lists = vcn_client.list_security_lists(compartment_id, vcn_id=vcn.id).data
        sec_list = sec_lists[0] if sec_lists else None

        subnets = vcn_client.list_subnets(compartment_id, vcn_id=vcn.id).data
        if subnets:
            return vcn, subnets[0], sec_list

        print_step("Creating missing subnet...")
        ads = identity_client.list_availability_domains(compartment_id).data
        subnet = vcn_client.create_subnet(oci.core.models.CreateSubnetDetails(
            compartment_id=compartment_id, vcn_id=vcn.id, cidr_block=SUBNET_CIDR,
            display_name="auto-subnet", dns_label="autoweb",
            security_list_ids=[sec_list.id] if sec_list else []
        )).data
        oci.wait_until(vcn_client, vcn_client.get_subnet(subnet.id), "lifecycle_state", "AVAILABLE")
        print_step(f"Subnet created: {subnet.id}")
        return vcn, subnet, sec_list

    print_step("Creating new VCN architecture...")
    
    # Create VCN
    vcn_details = CreateVcnDetails(
        cidr_block=VCN_CIDR,
        compartment_id=compartment_id,
        display_name="auto-created-vcn",
        dns_label="autovcn"
    )
    vcn = vcn_client.create_vcn(vcn_details).data
    
    # Wait for VCN to become available
    oci.wait_until(vcn_client, vcn_client.get_vcn(vcn.id), 'lifecycle_state', 'AVAILABLE')
    print_step(f"VCN created: {vcn.id}")

    # Create Internet Gateway
    igw_details = CreateInternetGatewayDetails(
        compartment_id=compartment_id,
        vcn_id=vcn.id,
        is_enabled=True,
        display_name="auto-created-igw"
    )
    igw = vcn_client.create_internet_gateway(igw_details).data
    print_step(f"Internet Gateway created: {igw.id}")

    # Create Route Table
    route_rules = [oci.core.models.RouteRule(
        destination="0.0.0.0/0",
        destination_type="CIDR_BLOCK",
        network_entity_id=igw.id
    )]
    rt_details = CreateRouteTableDetails(
        compartment_id=compartment_id,
        vcn_id=vcn.id,
        display_name="auto-created-rt",
        route_rules=route_rules
    )
    route_table = vcn_client.create_route_table(rt_details).data
    print_step(f"Route Table created: {route_table.id}")

    # Create Security List
    egress_rules = [
        EgressSecurityRule(
            destination="0.0.0.0/0",
            protocol="all",
            is_stateless=False
        )
    ]
    
    ingress_rules = [
        # Allow SSH (Port 22)
        IngressSecurityRule(
            source="0.0.0.0/0",
            protocol="6",  # TCP
            is_stateless=False,
            tcp_options=TcpOptions(
                destination_port_range=PortRange(min=22, max=22),
                source_port_range=PortRange(min=1, max=65535)
            )
        ),
        # Allow Port 11434
        IngressSecurityRule(
            source="0.0.0.0/0",
            protocol="6",  # TCP
            is_stateless=False,
            tcp_options=TcpOptions(
                destination_port_range=PortRange(min=11434, max=11434),
                source_port_range=PortRange(min=1, max=65535)
            )
        ),
        # Allow ICMP for diagnostics
        IngressSecurityRule(
            source="0.0.0.0/0",
            protocol="1",
            is_stateless=False,
            icmp_options=IcmpOptions(type=3, code=4)
        )
    ]

    sl_details = CreateSecurityListDetails(
        compartment_id=compartment_id,
        vcn_id=vcn.id,
        display_name="auto-created-sl",
        egress_security_rules=egress_rules,
        ingress_security_rules=ingress_rules
    )
    sec_list = vcn_client.create_security_list(sl_details).data
    print_step(f"Security List created: {sec_list.id}")

    # Create Subnet
    subnet_details = CreateSubnetDetails(
        compartment_id=compartment_id,
        vcn_id=vcn.id,
        cidr_block=SUBNET_CIDR,
        display_name="auto-created-subnet",
        route_table_id=route_table.id,
        security_list_ids=[sec_list.id],
        dns_label="autoweb"
    )
    subnet = vcn_client.create_subnet(subnet_details).data
    oci.wait_until(vcn_client, vcn_client.get_subnet(subnet.id), 'lifecycle_state', 'AVAILABLE')
    print_step(f"Subnet created: {subnet.id}")

    return vcn, subnet, sec_list

def launch_instance(compute_client, identity_client, compartment_id, subnet_id, ssh_key, availability_domain):
    instance_details = LaunchInstanceDetails(
        compartment_id=compartment_id,
        availability_domain=availability_domain,
        display_name="auto-instance-a1",
        shape=SHAPE,
        shape_config=LaunchInstanceShapeConfigDetails(
            ocpus=OCPUS,
            memory_in_gbs=MEMORY_IN_GBS
        ),
        source_details=InstanceSourceViaImageDetails(
            image_id=IMAGE_ID,
            boot_volume_size_in_gbs=BOOT_VOLUME_SIZE_GBS,
            source_type="image"
        ),
        create_vnic_details=CreateVnicDetails(
            subnet_id=subnet_id,
            assign_public_ip=True
        ),
        metadata={
            "ssh_authorized_keys": ssh_key
        }
    )
    
    return compute_client.launch_instance(instance_details)

def main():
    # 1. Read Config
    print_step("Loading OCI config from ~/.oci/config")
    try:
        config = from_file()
    except Exception as e:
        print_error(f"Failed to load OCI config: {e}")
        return

    global COMPARTMENT_ID
    COMPARTMENT_ID = config["tenancy"]
    
    ssh_key = read_ssh_key()
    
    # Initialize clients
    compute_client = oci.core.ComputeClient(config)
    vcn_client = oci.core.VirtualNetworkClient(config)
    identity_client = oci.identity.IdentityClient(config)

    # Get Availability Domains (PHX region assumed from Image ID)
    print_step("Fetching Availability Domains...")
    ads = identity_client.list_availability_domains(compartment_id=COMPARTMENT_ID).data
    ad_names = [ad.name for ad in ads]
    
    if not ad_names:
        print_error("No Availability Domains found.")
        return
    
    print_step(f"Found {len(ad_names)} Availability Domains: {ad_names}")

    # 2. Setup Network
    vcn, subnet, sec_list = get_or_create_network(vcn_client, identity_client, COMPARTMENT_ID)

    print_step("Starting instance creation loop...")
    print_step(f"Shape: {SHAPE}, OCPUs: {OCPUS}, RAM: {MEMORY_IN_GBS}GB")
    
    # 4. Loop retrying with adaptive backoff
    attempt = 1
    current_delay = RETRY_DELAY_SECONDS
    while True:
        for ad in ad_names:
            print(f"Attempt #{attempt}: Trying Availability Domain: {ad}")
            try:
                response = launch_instance(
                    compute_client, 
                    identity_client, 
                    COMPARTMENT_ID, 
                    subnet.id, 
                    ssh_key, 
                    ad
                )
                instance = response.data
                
                print_step(f"Instance launched successfully! ID: {instance.id}")
                print_step("Waiting for instance to reach RUNNING state...")
                
                # Wait for running state
                try:
                    instance = oci.wait_until(
                        compute_client, 
                        compute_client.get_instance(instance.id), 
                        'lifecycle_state', 
                        'RUNNING',
                        wait_duration_seconds=300
                    ).data
                except oci.exceptions.MaximumWaitTimeExceeded:
                    print_error("Instance did not reach RUNNING state within timeout, but creation succeeded. Check console.")
                    # Attempt to get IP anyway
                    pass
                
                # Get VNIC to find Public IP
                vnics = compute_client.list_vnic_attachments(
                    COMPARTMENT_ID, 
                    instance_id=instance.id
                ).data
                
                public_ip = None
                for vnic_att in vnics:
                    if vnic_att.lifecycle_state == 'ATTACHED':
                        vnic = vcn_client.get_vnic(vnic_att.vnic_id).data
                        if vnic.is_primary:
                            public_ip = vnic.public_ip
                            break
                
                if public_ip:
                    print("\n" + "="*60)
                    print(f"SUCCESS: Instance is RUNNING")
                    print(f"Public IP: {public_ip}")
                    print(f"SSH Command: ssh ubuntu@{public_ip}")
                    print("="*60 + "\n")
                else:
                    print_step("Instance is running, but Public IP could not be retrieved immediately.")

                return # Exit script on success

            except ServiceError as e:
                if "Out of host capacity" in str(e.message):
                    print_error(f"Out of host capacity in {ad}.")
                elif "too many requests" in str(e.message).lower() or "429" in str(e.code):
                    current_delay = int(current_delay * 1.5)
                    print_error(f"Rate limited. Next delay: {current_delay}s")
                else:
                    print_error(f"ServiceError: {e.message} (Code: {e.code})")
                    if e.code not in ['InternalError', 'NotAuthorizedOrNotFound']:
                        # If it's a config error, stop.
                        return
        
        attempt += 1
        print_step(f"All domains tried. Waiting {RETRY_DELAY_SECONDS}s before next cycle...")
        time.sleep(current_delay)

if __name__ == "__main__":
    main()