# Generated by: free fleet (llm_router)
import sys, os
from pathlib import Path
_WILLOW_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_WILLOW_ROOT / 'core'))
from build_rag_simple import index_repo
from core.db import get_connection

GITHUB = str(_WILLOW_ROOT.parent)

repos = [
    'agents',
    'Aionic-Claude-Skills', 
    'SAFE',
    'safe-app-dating-wellbeing',
    'safe-app-utety-chat',
    'vision-board',
    'die-namic-system',
]

for repo in repos:
    path = os.path.join(GITHUB, repo)
    if os.path.exists(path):
        print(f"Indexing {repo}...", flush=True)
        count = index_repo(path, repo)
        print(f"  {repo}: {count} chunks", flush=True)
    else:
        print(f"  SKIP {repo} (not found)", flush=True)

# Final totals
conn = get_connection()
cur = conn.cursor()
cur.execute('SELECT repo, COUNT(*) FROM chunks GROUP BY repo ORDER BY COUNT(*) DESC')
print("\nFINAL RAG TOTALS:")
total = 0
for repo, count in cur.fetchall():
    print(f"  {repo}: {count}")
    total += count
print(f"  TOTAL: {total}")
conn.close()
