# Generated by: Cerebras (llm_router) - fixed by orchestrator
import json, os, sys, shutil

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core import user_lattice

TEMPLATE_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(TEMPLATE_DIR))

def scaffold(config_path):
    with open(config_path, encoding="utf-8") as f:
        cfg = json.load(f)

    name = cfg["agent_name"]
    template_user = cfg.get("template_user", "__template__" + name + "__")

    # 1. Create agent directory
    agent_dir = os.path.join(REPO_ROOT, "agents", name)
    os.makedirs(agent_dir, exist_ok=True)
    print("[1] Created: " + agent_dir)

    # 2. Copy and fill AGENT_PROFILE.md
    profile_src = os.path.join(TEMPLATE_DIR, "AGENT_PROFILE.template.md")
    profile_dst = os.path.join(agent_dir, "AGENT_PROFILE.md")
    with open(profile_src, encoding="utf-8") as f:
        profile = f.read().replace("{{AGENT_NAME}}", name)
    with open(profile_dst, "w", encoding="utf-8") as f:
        f.write(profile)
    print("[2] Created: " + profile_dst)

    # 3. Create blank training file
    training_dir = os.path.join(REPO_ROOT, "training")
    os.makedirs(training_dir, exist_ok=True)
    training_file = os.path.join(training_dir, name + "_training.jsonl")
    if not os.path.exists(training_file):
        open(training_file, "w").close()
        print("[3] Created: " + training_file)
    else:
        print("[3] Exists:  " + training_file)

    # 4. Seed lattice from domains config
    seeded = 0
    for domain in cfg.get("domains", []):
        d_name = domain["name"]
        if "{{" in d_name:
            print("[4] SKIP placeholder domain: " + d_name)
            continue
        for temporal in domain.get("key_temporals", []):
            try:
                user_lattice.store(
                    username=template_user,
                    domain=d_name,
                    depth=domain["canonical_depth"],
                    temporal=temporal,
                    content="[SEED PLACEHOLDER] " + d_name + "/" + str(domain["canonical_depth"]) + "/" + temporal,
                    source="scaffold_v1"
                )
                seeded += 1
            except Exception as e:
                print("    WARN: " + str(e))
    print("[4] Seeded " + str(seeded) + " lattice nodes into " + template_user)

    # 5. Print checklist
    print("")
    print("=== NEXT STEPS ===")
    print("[ ] Fill in agents/" + name + "/AGENT_PROFILE.md")
    print("[ ] Generate seeds: use templates/new_agent/seed_prompt.template.md with fleet")
    print("[ ] Load seeds: python -c import scripts to store under " + template_user)
    print("[ ] Generate training data: training/" + name + "_training.jsonl")
    print("[ ] Register agent in agent_registry")
    print("[ ] Test: AgentEngine(username, " + chr(34) + name + chr(34) + ")")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scaffold.py <config.json>")
        sys.exit(1)
    scaffold(sys.argv[1])
